name: 'Setup Project'
description: 'Sets up Node.js, PNPM, and configures caching for faster builds'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  pnpm-version:
    description: 'PNPM version to use'
    required: false
    default: '8'
  registry-url:
    description: 'Node.js package registry URL'
    required: false
    default: 'https://registry.npmjs.org/'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
        enableCrossOsArchive: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile --reporter=append-only
