name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          enableCrossOsArchive: true

      - name: Install dependencies
        run: 'pnpm install --no-frozen-lockfile --reporter=append-only'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Type Checking
        run: pnpm -r exec tsc --noEmit

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

  docker-build-test:
    name: Test Docker Build
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infrastructure/docker/backend/Dockerfile
          target: development
          push: false
          tags: digital-footprint-tracker/backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Dashboard Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infrastructure/docker/dashboard/Dockerfile
          target: development
          push: false
          tags: digital-footprint-tracker/dashboard:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
